apiVersion: v2
name: bullet
description: A real-time query engine for very large data streams
type: application
version: 0.1.0
appVersion: "1.0.4"
home: https://github.com/SketchBench/bullet-k8s
# icon:
maintainers:
  - name: FraBle
    email: frankb2@illinois.edu
    url: https://github.com/FraBle
  - name: makamhareesh
    email: hmakam2@illinois.edu
    url: https://github.com/makamhareesh
  - name: mukrpe
    email: mkp5@illinois.edu
    url: https://github.com/mukrpe
sources:
  - https://github.com/bullet-db
  - https://bullet-db.github.io
annotations:
  artifacthub.io/signKey: |
    fingerprint: F6F77B76587337D518F42D9CE720A2903AF94931
    url: https://keybase.io/frable90/pgp_keys.asc
keywords:
  - apache
  - bullet
  - spark
  - storm
  - kafka
  - sketch
  - benchmark
dependencies:
  - name: kafka
    version: 13.0.3
    repository: https://charts.bitnami.com/bitnami
    alias: pubsub
    import-values:
      - child: service
        parent: pubsub
  - name: kafdrop
    version: 0.2.3
    repository: https://bedag.github.io/helm-charts
    alias: pubsubMonit
    condition: pubsubMonit.enabled
  - name: spark
    version: 5.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: spark.enabled
    import-values:
      - child: master
        parent: sparkBackend.cluster
  - name: hdfs
    version: 0.1.10
    repository: https://gradiant.github.io/charts
    condition: hdfs.enabled
    import-values:
      - child: nameNode
        parent: sparkBackend.hdfs
