{{- if and .Values.sparkBackend.metrics.enabled .Values.sparkBackend.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "common.names.fullname" . }}-spark-backend
  {{- if .Values.sparkBackend.metrics.podMonitor.namespace }}
  namespace: {{ .Values.sparkBackend.metrics.podMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- if .Values.sparkBackend.metrics.podMonitor.additionalLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.sparkBackend.metrics.podMonitor.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
    - port: "4040"
      path: /metrics/executors/prometheus/
      {{- if .Values.sparkBackend.metrics.podMonitor.interval }}
      interval: {{ .Values.sparkBackend.metrics.podMonitor.interval }}
      {{- end }}
      {{- if .Values.sparkBackend.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.sparkBackend.metrics.podMonitor.scrapeTimeout }}
      {{- end }}
  {{- range .Values.sparkBackend.metrics.podMonitor.extraMetricsEndpoints }}
    - port: {{ .port }}
      path: {{ .path }}
    {{- if $.Values.sparkBackend.metrics.podMonitor.interval }}
      interval: {{ $.Values.sparkBackend.metrics.podMonitor.interval }}
    {{- end }}
    {{- if $.Values.sparkBackend.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ $.Values.sparkBackend.metrics.podMonitor.scrapeTimeout }}
    {{- end }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
{{- end }}
