apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bullet.fullname" . }}-spark-backend
  labels:
    {{- include "bullet.labels" . | nindent 4 }}
    app.kubernetes.io/component: spark-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: spark-backend
      {{- include "bullet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.sparkBackend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: spark-backend
        {{- include "bullet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.sparkBackend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.sparkBackend.podSecurityContext | nindent 8 }}
      containers:
        - name: spark-backend
          securityContext:
            {{- toYaml .Values.sparkBackend.securityContext | nindent 12 }}
          image: "{{ .Values.sparkBackend.image.repository }}:{{ .Values.sparkBackend.image.tag }}"
          imagePullPolicy: {{ .Values.sparkBackend.image.pullPolicy }}
          env:
          - name: HADOOP_USER_NAME
            value: {{ .Values.sparkBackend.hdfsUser }}
          args:
            - spark-submit
            - --master
            # https://github.com/bitnami/charts/blob/master/bitnami/spark/templates/_helpers.tpl
            - {{ printf "spark://%s-spark-master-svc:%g" .Release.Name .Values.sparkBackend.cluster.clusterPort }}
            - --deploy-mode
            - client
            - --conf
            - {{ printf "spark.driver.host=%s-spark-backend-driver" (include "bullet.fullname" .) }}
            - --conf
            - {{ printf "spark.driver.port=%g" .Values.sparkBackend.driver.port }}
            - --conf
            - {{ printf "spark.driver.blockManager.port=%g" .Values.sparkBackend.driver.blockManagerPort }}
            - --conf
            - spark.driver.bindAddress=0.0.0.0
            - --conf
            - {{ printf "spark.executor.cores=%g" .Values.sparkBackend.executorCores }}
            - --conf
            - {{ printf "spark.executor.memory=%s" .Values.sparkBackend.executorMemory }}
            - --conf
            - {{ printf "spark.ui.prometheus.enabled=%t" .Values.sparkBackend.metrics.enabled }}
            - --conf
            - {{ printf "spark.metrics.appStatusSource.enabled=%t" .Values.sparkBackend.metrics.enabled }}
            - --conf
            - {{ printf "spark.sql.streaming.metricsEnabled=%t" .Values.sparkBackend.metrics.enabled }}
            - --class
            - com.yahoo.bullet.spark.BulletSparkStreamingMain
            - --jars
            - {{ .Values.sparkBackend.otherJars }}
            - {{ .Values.sparkBackend.jar }}
            - --bullet-spark-conf
            - {{ printf "%s/bullet_spark_settings.yaml" .Values.sparkBackend.configDir }}
          ports:
            - name: spark-ui
              containerPort: 4040
              protocol: TCP
            - name: driver
              containerPort: {{ .Values.sparkBackend.driver.port }}
              protocol: TCP
            - name: block-manager
              containerPort: {{ .Values.sparkBackend.driver.blockManagerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 4040
              path: /
          readinessProbe:
            httpGet:
              port: 4040
              path: /
          resources:
            {{- toYaml .Values.sparkBackend.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: {{ printf "%s/bullet_spark_settings.yaml" .Values.sparkBackend.configDir }}
              subPath: bullet_spark_settings.yaml
            - name: config
              mountPath: {{ printf "%s/dsl_schema.json" .Values.sparkBackend.schemaDir }}
              subPath: dsl_schema.json
      {{- with .Values.sparkBackend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sparkBackend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sparkBackend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "bullet.fullname" . }}
