{{- if and .Values.sparkBackend.metrics.enabled .Values.sparkBackend.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "bullet.fullname" . }}-spark-backend
  {{- if .Values.sparkBackend.metrics.podMonitor.namespace }}
  namespace: {{ .Values.sparkBackend.metrics.podMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "bullet.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  podMetricsEndpoints:
    - port: "4040"
      path: /metrics/executors/prometheus/
      {{- if .Values.sparkBackend.metrics.podMonitor.interval }}
      interval: {{ .Values.sparkBackend.metrics.podMonitor.interval }}
      {{- end }}
      {{- if .Values.sparkBackend.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.sparkBackend.metrics.podMonitor.scrapeTimeout }}
      {{- end }}
  {{- range .Values.sparkBackend.metrics.podMonitor.extraMetricsEndpoints }}
    - port: {{ .port }}
      path: {{ .path }}
    {{- if $.Values.sparkBackend.metrics.podMonitor.interval }}
      interval: {{ $.Values.sparkBackend.metrics.podMonitor.interval }}
    {{- end }}
    {{- if $.Values.sparkBackend.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ $.Values.sparkBackend.metrics.podMonitor.scrapeTimeout }}
    {{- end }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "bullet.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: spark-backend
{{- end }}
