apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bullet.fullname" . }}-ui
  labels:
    {{- include "bullet.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  {{- if not .Values.bullet.ui.autoscaling.enabled }}
  replicas: {{ .Values.bullet.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: ui
      {{- include "bullet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.bullet.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: ui
        {{- include "bullet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.bullet.ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.bullet.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          securityContext:
            {{- toYaml .Values.bullet.ui.securityContext | nindent 12 }}
          image: "{{ .Values.bullet.ui.image.repository }}:{{ .Values.bullet.ui.image.tag }}"
          imagePullPolicy: {{ .Values.bullet.ui.image.pullPolicy }}
          env:
          - name: PORT
            value: {{ .Values.bullet.ui.service.port | quote }}
          ports:
            - name: service
              containerPort: {{ .Values.bullet.ui.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: {{ .Values.bullet.ui.service.port }}
              path: /
          readinessProbe:
            httpGet:
              port: {{ .Values.bullet.ui.service.port }}
              path: /
          resources:
            {{- toYaml .Values.bullet.ui.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: {{ printf "%s/env-settings.json" .Values.bullet.ui.configDir }}
              subPath: bullet_ui_env_settings.json
      {{- with .Values.bullet.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bullet.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bullet.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "bullet.fullname" . }}
          items:
          - key: bullet_ui_pubsub_config.yaml
            path: pubsub_config.yaml
          - key: bullet_ui_query_config.yaml
            path: query_config.yaml
          - key: bullet_ui_schema.json
            path: schema.json
      volumes:
      - name: config
        configMap:
          name: {{ include "bullet.fullname" . }}
