apiVersion: v1
kind: Service
metadata:
  name: {{ include "bullet.fullname" . }}-ui
  labels:
    {{- include "bullet.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  selector:
    app.kubernetes.io/component: ui
    {{- include "bullet.selectorLabels" . | nindent 4 }}
  type: {{ .Values.bullet.ui.service.type }}
  ports:
  - name: ui
    protocol: TCP
    port: {{ .Values.bullet.ui.service.port }}
    targetPort: {{ .Values.bullet.ui.service.port }}
