{{- if .Values.webservice.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bullet.fullname" . }}-web-service
  labels:
    {{- include "bullet.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bullet.fullname" . }}-web-service
  minReplicas: {{ .Values.webservice.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.webservice.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.webservice.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.webservice.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.webservice.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.webservice.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
