apiVersion: v1
kind: Service
metadata:
  name: {{ include "bullet.fullname" . }}-web-service
  labels:
    {{- include "bullet.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-service
spec:
  selector:
    app.kubernetes.io/component: web-service
    {{- include "bullet.selectorLabels" . | nindent 4 }}
  type: {{ .Values.webservice.service.type }}
  ports:
  - name: web-service
    protocol: TCP
    port: {{ .Values.webservice.service.port }}
    targetPort: {{ .Values.webservice.service.port }}
